### ISSUE TITLE
Environment not determined error

### ISSUE THREAD

**Issue by JHSaunders** [indietyp/django-automated-logging#5]
I am getting this info logged after my static requests:

> Environment for request couldn't be determined. Request was not recorded.

for example:

```
02-28 11:44:33.741     INFO | automated_logging.signals.request.request_finished_signal:45   | Environment for request couldn't be determined. Request was not recorded.
```

This is not a problem in production, because static files are served separately, but it is a little confusing a noisy during development. Is there some error in my configuration? Or is there a way to exclude the static files from the logger?

I am just logging to the console, not to the using the database backend.

In case something else is stomping on an internal object, here is my middleware:
```python
[
            "django.middleware.security.SecurityMiddleware",
            "whitenoise.middleware.WhiteNoiseMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",            
            "django.contrib.messages.middleware.MessageMiddleware",
            "django_plotly_dash.middleware.BaseMiddleware",
            "django_plotly_dash.middleware.ExternalRedirectionMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
#          
# Some custom middleware that only affects the user model for impersonation
#
            "automated_logging.middleware.AutomatedLoggingMiddleware",
            "debug_toolbar.middleware.DebugToolbarMiddleware",
            "threadlocals.middleware.ThreadLocalMiddleware",
],
```

Otherwise thanks for a great project.

**Comment by indietyp** [comment]
Hey, thanks for the great issue!

That is indeed correct, you did nothing wrong. I just forgot to create an option to supress these errors. You can now toggle these messages using a new configuration option, starting with version 6.1.0.

```python
AUTOMATED_LOGGING = {
    ...
   'request': {
      ...
       'log_request_was_not_recorded': False
       ...
   },
   ...
}
```
in your settings.py

`...` indicates that this is just a snippet of the actual configuration dict.

Hopefully this resolved your issue.
