### ISSUE TITLE
The model Model_X is already registered

### ISSUE THREAD

**Issue by sikaili99** [indietyp/django-automated-logging#8]
When I run  ` python manage.py migrate automated_logging` I am getting errors that models are already registered.

**Comment by indietyp** [comment]
I need a bit more context:

* Have you been using DAL on the database/application previously? 
* What exactly is the error stacktrace?

I am sadly unable to help without further information.

**Comment by sikaili99** [comment]
I just wanted to use it in an already existing Django app and I don't have
similar model names as DAL but when I run migrate I am getting the same
error for all the models that are within DAL that is The mode name is
already registered.

**Comment by indietyp** [comment]
This does not answer my questions, I still have no clue what exactly is causing the problem. You can refer to #3 or #5 for great issue reports and data provided. Without any more information (like a stack trace) I am unable to reproduce the issue and help you.

**Comment by sikaili99** [comment]
Hey @indietyp 

I have not been using it previously, this is my first time.
The error is coming from the `admin` module where the models are registered via a decorator  e.g`@register(ModelEntry)`

**Comment by indietyp** [comment]
trying to replicate the issue, but without a traceback I am not of much help. A [traceback](https://www.geeksforgeeks.org/python-traceback/) should be printed with the error that happened, if you could provide such that traceback I could help you further and faster.
